name: "test-main"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-codebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .  # Set working directory to root.
    steps:
      # Check out the repository.
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Python 3.12.7.
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Cache the Poetry virtual environment located at .venv in the root.
      - name: Cache Poetry virtual environment
        id: poetry-cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.12.7-${{ hashFiles('poetry.lock') }}

      # Install Poetry if the cache was not hit.
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Install project dependencies.
      - name: Install dependencies
        run: poetry install --with=dev

      # Run static type analysis using mypy via Poetry.
      - name: Run static type analysis
        run: | 
          source .venv/bin/activate
          poetry run mypy --explicit-package-bases .
